name: Docker Image CI

on:
  push:
    branches: [ "docker" ]
  pull_request:
    branches: [ "docker" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Build and push to Docker Hub 
      uses: docker/build-push-action@v2
      with:
       context: .
       push: true
       tags: namhoaidoan15/buildingconstruct:latest, namhoaidoan15/buildingconstruct:${{github.run_number}}
